import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./components/provider";
import MainNavbar from "./components/mainNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shop Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <MainNavbar />
          <div className="flex-grow">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
